config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # get '/songs', to: 'songs#index', as: :songs
  # get '/songs/:id', to: 'songs#show', as: :song

  # get '/artists', to: 'artists#index', as: :artists
  # get '/artists/new', to: 'artists#new', as: :new_artist
  # post '/artists/new', to: 'artists#create'
  # get '/artists/:id/edit', to: 'artists#edit', as: :edit_artist
  # patch '/artists/:id', to: 'artists#update', as: :update_artist
  # delete '/artists/:id/delete', to: 'artists#destroy', as: :delete_artist
  resources :songs, only: [:index, :show]
  resources :artists, except: :show do
    resources :songs, only: [:new, :create, :index]
  end
  resources :users, only: [:new, :create, :show]

  get '/playlists', to: 'playlists#index'
  patch '/cart/:song_id', to: 'carts#add_song', as: :cart
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  namespace :admin do
    resources :articles, only: [:new, :create, :destroy]
  end
  
  resources :article, only: [:show, :index]

  # get '/artists/:artist_id/songs/new', to: 'songs#new', as: :new_song
  # get '/artists/:artist_id/songs', to: 'songs#artist_songs', as: :artist_songs
  # post 'artists/:artist_id/songs', to: 'songs#create', as: :new_artist_song
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  validates_presence_of :name

  def average_song_length
    songs.sum { |song| song.length } / songs.length
  end
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Hash.new(0)
    @contents.default = 0
  end

  def total_count
    @contents.values.sum
  end

  def add_song(id)
    @contents[id.to_s] += 1
  end

  def count_of(id)
    @contents[id.to_s].to_i
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
  belongs_to :artist
  validates_presence_of :title, :length

  def self.song_count
    Song.all.length
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :user_name, uniqueness: true, presence: true
  validates_presence_of :password, require: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :cart, :current_user

  def cart
    @cart ||= Cart.new(session[:cart])
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      flash[:notice] = "Artist not created: Required information missing."
      render :new
    end
  end

  def edit
  end

  def update
    @artist.update(artist_params)
    redirect_to artists_path
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def artist_params
    params.permit(:name)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def add_song
    song = Song.find(params[:song_id])
    cart.add_song(song.id)
    session[:cart] = cart.contents
    quantity = cart.count_of(song.id)
    flash[:success] = "You now have #{pluralize(quantity, 'copy')} of #{song.title} in your cart."
    redirect_to songs_path
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  #before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  def index
    @playlists = Playlist.all
  end

  # private
  #
  # def playlist_params
  #   params.permit(:name)
  # end
  #
  # def set_playlist
  #   @playlist = Playlist.find(params[:id])
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(user_name: params[:user_name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "You have been logged out."
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    if params[:artist_id].nil?
      @songs = Song.all
    else
      @artist = Artist.find(params[:artist_id])
      @songs = Song.all.select { |song| song.artist_id == @artist.id }
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  def create
    artist = Artist.find(params[:artist_id])
    song = artist.songs.create!(song_params)
    redirect_to song_path(song)
  end

  private

  def song_params
    params.permit(:title, :length, :play_count)
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.permit(:user_name, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<h1><%= "#{title}" %></h1>

<%= form_tag path, method: method do %>
  <%= label_tag :name %>
  <%= text_field_tag :name, @artist.name %><br/>
  <br/>
  <%= submit_tag button_text %>
<% end %>

app/views/artists/edit.html.erb
<%= render 'form', title: 'Edit Artist', path: artist_path, method: :patch, button_text: 'Edit Artist' %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<% @artists.each do |artist| %>
  <h2><%= artist.name %>
    <%= link_to 'Edit', edit_artist_path(artist), method: :get %>
    <%= link_to 'Delete', artist_path(artist), method: :delete %></h2>
<% end %>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<%= render 'form', title: 'New Artist', path: artists_path, method: :post, button_text: 'Create Artist' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SetList</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"%>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="nav">
      <a class="nav-link active" href="/artists">Artists</a>
      <a class="nav-link active">Cart: <%= cart.total_count %></a>
    </nav>

    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: type %>
    <% end %>

    <% if @current_user %>
      <h1>Welcome, <%= @current_user.user_name %>!</h1>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/playlists/index.html.erb
<% @playlists.each do |playlist| %>
  <section id="playlist-<%= playlist.id %>">
    <h1><%= playlist.name %></h1>
    <% playlist.songs.each do |song| %>
      <section id="song-<%= song.id %>">
        <p><%= song.title %></p>
      </section>
    <% end %>
  </section>
<% end %>

app/views/songs/index.html.erb
<h1 id='title'>
  All Songs
  <% unless @artist.nil? %>
    for
    <%= @artist.name %>
  <% end %>
</h1>

<% @songs.each do |song| %>
  <section id='song-<%= song.id %>' class='song'>
    <h2><%= song.title %></h2>
    <p>Play Count: <%= song.play_count %></p>
    <%= button_to "Add Song", cart_path(song), method: :patch %>
  </section>
<% end %>

app/views/songs/new.html.erb
<%= form_tag(artist_songs_path(@artist), method: :post) do %>
  <%= label_tag :title %>
  <%= text_field_tag :title %>

  <%= label_tag :length %>
  <%= number_field_tag :length %>

  <%= label_tag :play_count %>
  <%= number_field_tag :play_count %>

  <%= submit_tag "Create Song"%>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1><br/>
<h2><%= @song.length %></h2><br/>
<h2><%= @song.play_count %></h2><br/>

<p>By: <%= @song.artist.name %></p>

app/views/users/new.html.erb
<%= form_tag users_path do %>
  <%= label_tag :user_name, 'User Name' %>
  <%= text_field_tag :user_name %>

  <%= label_tag :password, 'Password' %>
  <%= text_field_tag :password %>

  <%= submit_tag 'Create User' %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.user_name %>!</h1>
<%= link_to 'Log out', logout_path %>

app/views/welcome/index.html.erb
<%= link_to 'Register as a User', new_user_path %>
<%= link_to 'I already have an account', login_path %>